"""create economic_releases and release_occurrences tables

Revision ID: 42114760e4c8
Revises: 6412695f6f9d
Create Date: 2026-09-13 10:56:17.811719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42114760e4c8'
down_revision: Union[str, Sequence[str], None] = '6412695f6f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='FRED', nullable=False),
    sa.Column('provider_release_id', sa.String(length=64), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_release_id', name='uq_release_provider_provider_release_id')
    )
    op.create_table('release_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('economic_release_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['economic_release_id'], ['economic_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('economic_release_id', 'scheduled_date', name='uq_occurrence_release_scheduled_date')
    )
    op.create_index(op.f('ix_release_occurrences_economic_release_id'), 'release_occurrences', ['economic_release_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_occurrences_economic_release_id'), table_name='release_occurrences')
    op.drop_table('release_occurrences')
    op.drop_table('economic_releases')
    # ### end Alembic commands ###
