"""create economic_series and economic_observations tables

Revision ID: 6412695f6f9d
Revises: 
Create Date: 2026-09-11 11:59:44.514569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6412695f6f9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('units', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), server_default='FRED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_series_series_id'), 'economic_series', ['series_id'], unique=True)
    op.create_table('economic_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('economic_series_id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['economic_series_id'], ['economic_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('economic_series_id', 'observation_date', name='uq_observation_series_date')
    )
    op.create_index(op.f('ix_economic_observations_economic_series_id'), 'economic_observations', ['economic_series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_economic_observations_economic_series_id'), table_name='economic_observations')
    op.drop_table('economic_observations')
    op.drop_index(op.f('ix_economic_series_series_id'), table_name='economic_series')
    op.drop_table('economic_series')
    # ### end Alembic commands ###
