"""create release_series_mappings, release_check_runs, release_observation_updates, and release_analysis_updates

Revision ID: dbd9a2889ef3
Revises: fbbe6b1ab8d9
Create Date: 2026-09-13 15:36:22.202269

Increment #18's schema (see docs/architecture/release-processing-v1.md).
Schema only -- creates no rows; the curated CPI/PIO release->series
mappings are a separate, deliberately later migration (mirroring the
existing #17A pattern of 42114760e4c8/fbbe6b1ab8d9), so this one can be
downgraded/re-applied without ever touching product-curation data.

`release_series_mappings.series_id` is a plain string, NOT a foreign
key to `economic_series.id` -- see app/db/models.py's
ReleaseSeriesMapping docstring. `release_check_runs.status` has no
persisted "DB failure" value; a transaction failure means this row
(and everything else in that attempt) never durably exists at all,
by design. `release_observation_updates` is append-only and never
records UNCHANGED. `release_analysis_updates.evaluation_period` is a
single column (not previous/current) because release-scoped before/
after evidence is always evaluated at the same calendar period -- see
that model's own docstring for why this is not
`inflation_what_changed_v1.0`'s ChangeEvent shape distorted, but its
honest release-scoped equivalent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd9a2889ef3'
down_revision: Union[str, Sequence[str], None] = 'fbbe6b1ab8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_series_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('economic_release_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['economic_release_id'], ['economic_releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('economic_release_id', 'series_id', name='uq_release_series_mapping_release_series')
    )
    op.create_index(op.f('ix_release_series_mappings_economic_release_id'), 'release_series_mappings', ['economic_release_id'], unique=False)
    op.create_table('release_check_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_occurrence_id'], ['release_occurrences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_check_runs_release_occurrence_id'), 'release_check_runs', ['release_occurrence_id'], unique=False)
    op.create_table('release_analysis_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_check_run_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('previous_value', sa.String(length=64), nullable=True),
    sa.Column('current_value', sa.String(length=64), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('evaluation_period', sa.Date(), nullable=False),
    sa.Column('methodology_id', sa.String(length=32), nullable=False),
    sa.Column('data_basis', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_check_run_id'], ['release_check_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_analysis_updates_release_check_run_id'), 'release_analysis_updates', ['release_check_run_id'], unique=False)
    op.create_table('release_observation_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_check_run_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_check_run_id'], ['release_check_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_check_run_id', 'series_id', 'observation_date', name='uq_release_observation_update_run_series_date')
    )
    op.create_index(op.f('ix_release_observation_updates_release_check_run_id'), 'release_observation_updates', ['release_check_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_observation_updates_release_check_run_id'), table_name='release_observation_updates')
    op.drop_table('release_observation_updates')
    op.drop_index(op.f('ix_release_analysis_updates_release_check_run_id'), table_name='release_analysis_updates')
    op.drop_table('release_analysis_updates')
    op.drop_index(op.f('ix_release_check_runs_release_occurrence_id'), table_name='release_check_runs')
    op.drop_table('release_check_runs')
    op.drop_index(op.f('ix_release_series_mappings_economic_release_id'), table_name='release_series_mappings')
    op.drop_table('release_series_mappings')
    # ### end Alembic commands ###
