"""create maintenance_sweeps

Revision ID: f12b7ec0d626
Revises: 09f4c0959e9f
Create Date: 2026-09-15 00:01:15.628537

Increment #25C's automated-economic-maintenance sweep record (see
docs/product/automated-economic-maintenance-v1.md §53/§54). One row
per bounded orchestrator sweep attempt -- deliberately NOT
`release_check_runs` (per-occurrence, economic-check-shaped data);
this table is per-ORCHESTRATOR-RUN, operational-health-shaped data,
kept separate so "did the automation worker itself run" is never
conflated with "was a specific release occurrence's own check
successful" (frozen contract §30). `finished_at`/`status`/the three
count columns are all nullable and written together, once, at sweep
completion -- a row with `finished_at IS NULL` means the sweep started
and has not (yet, or ever) finished, the intentional signal a future
health check needs to distinguish a crashed/still-running sweep from
"no sweep ran at all" (no row exists).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12b7ec0d626'
down_revision: Union[str, Sequence[str], None] = '09f4c0959e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_sweeps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('due_count', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_sweeps')
    # ### end Alembic commands ###
